source "https://rubygems.org"

# Specify your gem's dependencies in ruby_fundamentals.gemspec

gem "rake", "~> 12.0"


gem "require_all", "~> 3.0"
gem "colorize", "~> 0.8.1"

group :development do 
  gem "pry", "~> 0.14.1"
end

gem "activesupport", "6.1"

gem "sqlite3", "~> 1.4"

gem "activerecord", "~> 6.1"
gem "sinatra-activerecord", "~> 2.0"